build:
    image: kradalby/ci-tox:latest
    pull: true
    commands:
      - tox

notify:
  email:
    from: drone@fap.no
    host: smtp.stud.ntnu.no
    port: 25
    recipients:
      - kradalby@kradalby.no
